### ISSUE TITLE
[Bug] my-workflow.yml is incorrect; doesn't lint

### ISSUE THREAD

**Issue by anujdeshpande** [skills/writing-javascript-actions#3]
**Describe the bug**
I think the yml describing the  full file after edits is incorrect
I used http://www.yamllint.com/ to check whether it lints as well

**To Reproduce**
1. Go to ['yaml lint'](http://www.yamllint.com/)
2. Paste the following
```
- name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

     	 - name: ha-ha
         uses: ./.github/actions/joke-action
```
3.  See errors `(<unknown>): did not find expected '-' indicator while parsing a block collection at line 1 column 1`
4. You can see a live example of this fails on my repo here - https://github.com/anujdeshpande/test-action/actions/runs/2660634776/workflow

**Expected behavior**
The yml should lint. 

**Screenshots**

![image](https://user-images.githubusercontent.com/969376/178639137-8dc3c1ef-4ba9-4205-ada1-7acbf19d8120.png)
